spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hzgitls/config-server-repo
          username: 13735560295@163.com
          password: hzgitls13735560295
          timeout: 3000
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/


env:
  dev2
  
girl:
  name: lili
  age: 19
